### ISSUE TITLE
Modal Display Issue on Different Devices

### ISSUE THREAD

**Issue by RambunctiousCookie** [reown-com/reown-dotnet#28]
Am encountering inconsistency in the default display modal when it comes to different devices.

The modal is fine when run on Emulator and Unity

The icons are fairly tiny in Unity (I took a look at [samples](https://docs.reown.com/appkit/unity/core/customization) but there is no specific setting or documentation on increasing icon size).

Attached are images of the modal when built to Android and run on several different platforms. 

Emulator works the best, Unity Modal UI is too small and S10 will not even show the modal for some reason?

![modal-issue-censor](https://github.com/user-attachments/assets/bdda4b2d-a0d9-4d3f-a796-c2ab36a8a16c)

**Comment by skibitsky** [comment]
Hey @RambunctiousCookie,

The AppKit UI is responsive and works differently on desktop and mobile platform. When you select mobile platform in the Editor, the AppKit follows mobile layout rules. However, your desktop screen resolution, pixel density, and `Game` window size are very unusual for the mobile platform which usually makes the UI elements to small.

For the accurate UI in the Editor I recommend to use `Simulator` instead of the `Game`:
<img width=500 src="https://github.com/user-attachments/assets/47b09773-f33a-42e9-b0b2-30b004e8899b"/>

---

As for the issue on Samsung S10, it most likely has been addressed [v1.1.0](https://github.com/reown-com/reown-dotnet/releases/tag/com.reown.appkit.unity%2F1.1.0). I recommend upgrading to the latest version.

In another issue you mentioned connectivity issues in v1.2.0. If that blocks you from upgrading, please open a new issue and provide your AppKit configuration code and project id.
